# Generated by Django 5.0 on 2024-01-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='քարեր', max_length=30, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='ձեռնաշղթաներ', max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(default='քարեր', max_length=30, verbose_name='Тег'),
        ),
    ]
