# Generated by Django 5.0 on 2024-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bracelets', 'Բրասլետներ'), ('rings', 'Մատանիներ'), ('earrings', 'Ականջօղներ'), ('necklaces', 'Վզնոցներ'), ('colognes', 'Կուլոններ'), ('other', 'Այլ')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
